import "./globals.css";
import localFont from "next/font/local";
import Script from "next/script";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./Header";
import Footer from "./Footer";
import Providers from "./Providers";

// @font-face {
//   font-family: iransans;
//   src: url('../fonts/iransans/IRANSansX-Black.woff') format('woff');
//   font-weight: 900;
// }

// @font-face {
//   font-family: iransans;
//   src: url('../fonts/iransans/IRANSansX-Bold.woff') format('woff');
//   font-weight: 700;
// }

// @font-face {
//   font-family: iransans;
//   src: url('../fonts/iransans/IRANSansX-DemiBold.woff') format('woff');
//   font-weight: 600;
// }

// @font-face {
//   font-family: iransans;
//   src: url('../fonts/iransans/IRANSansX-Medium.woff') format('woff');
//   font-weight: 500;
// }

// @font-face {
//   font-family: iransans;
//   src: url('../fonts/iransans/IRANSansX-Regular.woff') format('woff');
//   font-weight: normal;
// }

// @font-face {
//   font-family: 'iransansxv';
//   src: url('../fonts/iransans/IRANSansXV.woff') format('woff-variations'),
// 	/* will be the standard and works in Safari now */
//   url('../fonts/iransans/IRANSansXV.woff') format('woff');
//   /* for the other supporting browsers */
//   font-weight: 100 900;
//   font-display: fallback;
// }

const iransans = localFont({
  src: [
    { path: "../public/fonts/iransans/IRANSansX-Black.woff", weight: "900" },
    { path: "../public/fonts/iransans/IRANSansX-Bold.woff", weight: "700" },
    { path: "../public/fonts/iransans/IRANSansX-DemiBold.woff", weight: "600" },
    { path: "../public/fonts/iransans/IRANSansX-Medium.woff", weight: "500" },
    {
      path: "../public/fonts/iransans/IRANSansX-Regular.woff",
      weight: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={iransans.className} dir="rtl">
        <Providers>
          <Header />
          <div className="flex flex-col h-full bg-gray-100 py-2">
            {children}
          </div>
          <Footer />
        </Providers>
      </body>

      <Script id="gofino" strategy="lazyOnload">
        {`!function(){var i="aj5JNn",a=window,d=document;function g(){var g=d.createElement("script"),s="https://www.goftino.com/widget/"+i,l=localStorage.getItem("goftino_"+i);g.async=!0,g.src=l?s+"?o="+l:s;d.getElementsByTagName("head")[0].appendChild(g);}"complete"===d.readyState?g():a.attachEvent?a.attachEvent("onload",g):a.addEventListener("load",g,!1);}();`}
      </Script>
    </html>
  );
}
